[project]
name = "naics-editor"
version = "0.2.0"
description = "FastAPI app to search and edit NAICS codes."
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "polars",
    "pyarrow",
    "requests",
    "duckdb",
    "lancedb",
]

[tool.ruff]